[General]
%2B8gcPZIuASRcihpYJW6UA83rPnH%2B7ifu11s9xp3p8Rc%23=1760645404
63tJmSFEpYg9dR34FZPBHK8VKGPcUT1yDVJWSS9UTuU%23=1760645404
GeoLocale=system
KXhiCZ2HpmjrAEVlAVyB4VHAVsfnyTQR06weNL9BKYY%23=1760645404
QFmw49Tp2Lqtyhswu7RnGrEMJ0VJdjm%2By6zXSVlOAAA%23=1760645404
SensitiveInfoMaskOn=true
ShowBiDirecSyncNoti=true
UeJ7AgrtBappnQjaaFui4jk8yVCY2K4zE14gyE34Rzo%23=1760645404
a1Sc6Vo9iXZJc6iPe7ITjh0sHFsyTlZ7tcm0G74sUk8%23=1760645404
autoPlayGif=false
autoScale=true
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
chatListPanelLastWidth=230
com.disable.connection.pk.status=false
com.zoom.client.langid=0
conf.webserver=https://us02web.zoom.us
conf.webserver.vendor.default=https://u.zoom.us
currentMeetingId=84751378515
deviceID=80:FA:5B:9D:BF:0A
disableCef=false
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCefGpu=false
enableCefLog=false
enableCefTa=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
hideCrashReport=false
host.auto.grab.interval=10
isTransCoding=false
jK9BkbV8zNjw7whdX9AnddbmbOu4N8hVKwVt8iDnC38%23=1760645404
logLevel=info
newMeetingWithVideo=true
noSandbox=false
pOoALJyX%2BqjXWD3Cr1Q4lH5ZpVshFjYob0SH3xBr2jQ%23=1760645404
playSoundForNewMessage=false
shareBarTopMargin=0
showOneTimePTAICTipHubble=false
showOneTimeQAMostUpvoteHubble=true
showOneTimeQueriesOptionTip=true
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
systemDockMargin=0
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=u0977428@utah.edu
webview.debug.enable=false
xwayland=true

[1VGa6fEsTQYEquYOdMv]
j1V5NQSTWNQPlSB8TSaIgvM%23=1760645404

[AS]
showframewindow=true

[CodeSnippet]
lastCodeType=0
wrapMode=0

[chat.recent]
recentlast.session=

[e2oewir4]
zlsEjhEtnrfV\1\RNfupD3GFHXnLPoOTzI%23=1760645404

[p2j01nOS5WVbsNRvQFnMTmH5SbwLdPoVQxAt]
B0jJHc%23=1760645404

[pvKc9SrvNy]
UrM6djKC7sBYYhjF2xNCSHVpXDpFealQ%23=1760645404

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="631,600"
main_frame_pixel_pos_wide="1269,960"
