github.com:
    users:
        richbai90:
            oauth_token: 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
    git_protocol: ssh
    user: richbai90
    oauth_token: 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
