github.com:
    users:
        richbai90:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: richbai90
